name: WakaTime Stats with Graph

on:
  schedule:
    - cron: '0 0 * * *'   # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update WakaTime README
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_OS: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_COMMIT: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "True"    # Enables bar graph
